timeLimiter.enabled : true
circuitBreaker.enabled : true
runLoadInternally.enabled : false
printMetrics.enabled: false

blockhound.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric